import { env } from '../config/env.js';

export type SearchResult = { provider: 'spotify' | 'youtube'; providerId: string; title: string; artists: string[]; album?: string; artworkUrl?: string; externalUrl: string; durationMs?: number; releaseDate?: string; popularity?: number; channel?: string; publishedAt?: string; metadata: Record<string, unknown> };
type ProviderSearch = { provider: 'spotify' | 'youtube'; enabled: boolean; results: SearchResult[]; message?: string };
let spotifyToken: { value: string; expiresAt: number } | undefined;

async function spotifyAccessToken() { if (spotifyToken && spotifyToken.expiresAt > Date.now()) return spotifyToken.value; if (!env.spotifyClientId || !env.spotifyClientSecret) throw new Error('Spotify is not configured.'); const auth = Buffer.from(`${env.spotifyClientId}:${env.spotifyClientSecret}`).toString('base64'); const response = await fetch('https://accounts.spotify.com/api/token', { method: 'POST', headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/x-www-form-urlencoded' }, body: 'grant_type=client_credentials' }); if (!response.ok) throw new Error('Spotify authentication failed.'); const payload = await response.json() as { access_token: string; expires_in: number }; spotifyToken = { value: payload.access_token, expiresAt: Date.now() + (payload.expires_in - 60) * 1000 }; return spotifyToken.value; }

async function searchSpotify(query: string): Promise<ProviderSearch> { if (!env.spotifyClientId || !env.spotifyClientSecret) return { provider: 'spotify', enabled: false, results: [], message: 'Add Spotify credentials to enable results.' }; const token = await spotifyAccessToken(); const response = await fetch(`https://api.spotify.com/v1/search?${new URLSearchParams({ q: query, type: 'track', limit: '12', market: 'IN' })}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Spotify search failed.'); const payload = await response.json() as { tracks: { items: Array<{ id: string; name: string; artists: Array<{ name: string }>; album: { name: string; images: Array<{ url: string }> ; release_date?: string }; duration_ms: number; external_urls: { spotify: string }; popularity: number }> } }; return { provider: 'spotify', enabled: true, results: payload.tracks.items.map(track => ({ provider: 'spotify', providerId: track.id, title: track.name, artists: track.artists.map(artist => artist.name), album: track.album.name, artworkUrl: track.album.images[0]?.url, externalUrl: track.external_urls.spotify, durationMs: track.duration_ms, releaseDate: track.album.release_date, popularity: track.popularity, metadata: { popularity: track.popularity } })) }; }

async function searchYoutube(query: string): Promise<ProviderSearch> { if (!env.youtubeApiKey) return { provider: 'youtube', enabled: false, results: [], message: 'Add a YouTube Data API key to enable results.' }; const search = await fetch(`https://www.googleapis.com/youtube/v3/search?${new URLSearchParams({ part: 'snippet', q: query, type: 'video', maxResults: '12', key: env.youtubeApiKey })}`); if (!search.ok) throw new Error('YouTube search failed.'); const payload = await search.json() as { items: Array<{ id: { videoId: string }; snippet: { title: string; channelTitle: string; publishedAt: string; thumbnails: { high?: { url: string }; medium?: { url: string }; default?: { url: string } } } }> }; return { provider: 'youtube', enabled: true, results: payload.items.map(video => ({ provider: 'youtube', providerId: video.id.videoId, title: video.snippet.title.replaceAll('&quot;', '"'), artists: [video.snippet.channelTitle], artworkUrl: video.snippet.thumbnails.high?.url ?? video.snippet.thumbnails.medium?.url ?? video.snippet.thumbnails.default?.url, externalUrl: `https://www.youtube.com/watch?v=${video.id.videoId}`, channel: video.snippet.channelTitle, publishedAt: video.snippet.publishedAt, metadata: { channel: video.snippet.channelTitle, publishedAt: video.snippet.publishedAt } })) }; }

export async function searchProviders(query: string) { const [spotify, youtube] = await Promise.allSettled([searchSpotify(query), searchYoutube(query)]); return [spotify.status === 'fulfilled' ? spotify.value : { provider: 'spotify' as const, enabled: true, results: [], message: spotify.reason instanceof Error ? spotify.reason.message : 'Spotify is unavailable.' }, youtube.status === 'fulfilled' ? youtube.value : { provider: 'youtube' as const, enabled: true, results: [], message: youtube.reason instanceof Error ? youtube.reason.message : 'YouTube is unavailable.' }]; }
