import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { api, ApiError, LibraryEntry, SearchGroup, SearchResult, Session } from './services/api';

type Theme = 'dark' | 'light';
type Song = { id: string; title: string; artist: string; album: string; tags: string[]; rating: number; artworkUrl?: string; favorite: boolean; notes: string; added: string };
const nav = ['Overview', 'Library', 'Favorites', 'Collections', 'Analytics', 'Tags'];
function Stars({ value }: { value: number }) { return <span className="stars">{'*'.repeat(Math.round(value))}</span>; }
function NavIcon({ name }: { name: string }) { const paths: Record<string, string> = { Overview: 'M3 11.5 12 4l9 7.5v8a1 1 0 0 1-1 1h-5v-6h-6v6H4a1 1 0 0 1-1-1z', Library: 'M4 4h16v16H4z M8 4v16 M12 8h5 M12 12h5', Favorites: 'M12 20s-7-4.5-7-10a4 4 0 0 1 7-2.6A4 4 0 0 1 19 10c0 5.5-7 10-7 10z', Collections: 'M4 6h16v4H4z M4 14h16v4H4z', Analytics: 'M4 19V9 M10 19V5 M16 19v-7 M22 19H2' }; return <svg className="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]} fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
function toSong(entry: LibraryEntry): Song { return { id: entry._id, title: entry.musicRecordId.title, artist: entry.musicRecordId.artists.join(', '), album: entry.musicRecordId.album || 'Single', tags: entry.tags, rating: entry.rating || .5, artworkUrl: entry.musicRecordId.artworkUrl, favorite: entry.favorite, notes: entry.notes || '', added: new Date(entry.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }; }

function SettingsPage({ theme, onToggleTheme }: { theme: Theme; onToggleTheme: () => void }) {
  const [sort, setSort] = useState(() => localStorage.getItem('music-journal-sort') ?? 'Recently added');
  const [compact, setCompact] = useState(() => localStorage.getItem('music-journal-compact') === 'true');
  const saveSort = (value: string) => { setSort(value); localStorage.setItem('music-journal-sort', value); };
  const saveCompact = (value: boolean) => { setCompact(value); localStorage.setItem('music-journal-compact', String(value)); };
  return <section className="settings-page"><p className="eyebrow">PREFERENCES</p><h1>Settings</h1><p className="subhead">Make your journal feel like your own.</p><div className="settings-card"><div><b>Appearance</b><span>Choose the journal background.</span></div><button className="settings-action" onClick={onToggleTheme}>Use {theme === 'dark' ? 'light' : 'dark'} mode</button></div><div className="settings-card"><div><b>Default library sort</b><span>Applied whenever you open your library.</span></div><select value={sort} onChange={e => saveSort(e.target.value)}><option>Recently added</option><option>Highest rated</option><option>Alphabetical</option></select></div><div className="settings-card"><div><b>Compact cards</b><span>Use a denser layout for your library.</span></div><label className="switch"><input type="checkbox" checked={compact} onChange={e => saveCompact(e.target.checked)}/><span></span></label></div><div className="settings-card"><div><b>Data ownership</b><span>Your journal entries and provider metadata are stored in your private MongoDB database.</span></div></div></section>;
}

function CollectionsPage({ library }: { library: Song[] }) { const collections = [{ name: 'Favorites', description: 'The songs you never tire of.', songs: library.filter(song => song.favorite) }, { name: 'Top rated', description: 'Songs rated 4.5 stars and above.', songs: library.filter(song => song.rating >= 4.5) }, { name: 'Recently added', description: 'Your most recent musical chapters.', songs: library }, ...Array.from(new Set(library.flatMap(song => song.tags))).filter(Boolean).slice(0,12).map(tag => ({ name: tag, description: 'Songs grouped by your journal tag.', songs: library.filter(song => song.tags.includes(tag)) }))]; const [selected, setSelected] = useState('Favorites'); const chosen = collections.find(collection => collection.name === selected) ?? collections[0]; return <section className="collection-page"><p className="eyebrow">SMART COLLECTIONS</p><h1>Your music, naturally organized.</h1><p className="subhead">Collections update automatically as your journal grows. Select one to see its songs.</p><div className="collection-grid">{collections.map((collection,index) => <button className={'collection-card '+(collection.name === selected ? 'selected' : '')} onClick={() => setSelected(collection.name)} key={collection.name}><span className={'collection-orb collection-'+index}>{collection.name.slice(0,1)}</span><div><h3>{collection.name}</h3><p>{collection.description}</p><b>{collection.songs.length} {collection.songs.length === 1 ? 'song' : 'songs'}</b></div></button>)}</div>{chosen && <section className="collection-songs"><div className="section-heading"><div><p className="eyebrow">COLLECTION</p><h2>{chosen.name}</h2></div></div><div className="song-grid">{chosen.songs.map(song => <article className="song-card" key={song.id}><div className="cover" style={song.artworkUrl ? { backgroundImage: `url(${song.artworkUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' } : {}}><span>{song.favorite ? 'Favorite' : song.tags[0] || 'Journal'}</span></div><div className="song-info"><h3>{song.title}</h3><p>{song.artist}</p><div><Stars value={song.rating}/><span className="tag">{song.tags.join(', ')}</span></div></div></article>)}</div>{!chosen.songs.length && <p className="empty">No songs in this collection yet.</p>}</section>}</section>; }

function AnalyticsPage({ library }: { library: Song[] }) { const average = library.length ? (library.reduce((sum, song) => sum + song.rating, 0) / library.length).toFixed(1) : '0.0'; const ratings = [5,4,3,2,1].map(value => ({ value, count: library.filter(song => Math.floor(song.rating) === value).length })); const tags = Array.from(new Set(library.flatMap(song => song.tags))).filter(Boolean).slice(0,5); return <section className="analytics-page"><p className="eyebrow">YOUR LISTENING STORY</p><h1>Analytics</h1><p className="subhead">A quiet look at the music you choose to keep.</p><div className="analytics-summary"><article><strong>{library.length}</strong><span>Saved songs</span></article><article><strong>{library.filter(song => song.favorite).length}</strong><span>Favorites</span></article><article><strong>{average}</strong><span>Average rating</span></article></div><div className="analytics-grid"><section className="analytics-card"><h2>Rating distribution</h2>{ratings.map(item => <div className="rating-row" key={item.value}><span>{item.value} stars</span><div><i style={{ width: `${library.length ? (item.count / library.length) * 100 : 0}%` }}></i></div><b>{item.count}</b></div>)}</section><section className="analytics-card"><h2>Top tags</h2>{tags.length ? tags.map(tag => <div className="tag-row" key={tag}><span>{tag}</span><b>{library.filter(song => song.tags.includes(tag)).length} songs</b></div>) : <p className="empty">Add tags to see your musical themes.</p>}</section></div></section>; }

function TagsPage({ token, onChanged }: { token: string; onChanged: () => void }) { const [tags, setTags] = useState<{name:string;count:number}[]>([]); const [editing, setEditing] = useState(''); const [name, setName] = useState(''); useEffect(() => { api.tags(token).then(response => setTags(response.data)); }, [token]); const rename = async (oldName: string) => { if (!name.trim()) return; await api.renameTag(token, oldName, name.trim()); setTags(items => items.map(item => item.name === oldName ? { ...item, name: name.trim() } : item)); setEditing(''); onChanged(); }; return <section className="tags-page"><p className="eyebrow">JOURNAL ORGANIZATION</p><h1>Tags</h1><p className="subhead">Rename a tag to update it everywhere in your journal.</p><div className="tags-list">{tags.map(tag => <article className="tag-editor" key={tag.name}>{editing === tag.name ? <><input autoFocus value={name} onChange={e => setName(e.target.value)}/><button className="settings-action" onClick={() => rename(tag.name)}>Save</button><button className="plain-button" onClick={() => setEditing('')}>Cancel</button></> : <><div><b>{tag.name}</b><span>{tag.count} {tag.count === 1 ? 'song' : 'songs'}</span></div><button className="settings-action" onClick={() => { setEditing(tag.name); setName(tag.name); }}>Edit</button></>}</article>)}</div>{!tags.length && <p className="empty">Tags appear after you save songs with tags.</p>}</section>; }

function EditSongModal({ token, song, onClose, onSaved }: { token: string; song: Song; onClose: () => void; onSaved: (song: Song) => void }) { const [rating, setRating] = useState(song.rating); const [tags, setTags] = useState(song.tags.join(', ')); const [notes, setNotes] = useState(song.notes); const [favorite, setFavorite] = useState(song.favorite); const [error, setError] = useState(''); const save = async (e: FormEvent) => { e.preventDefault(); try { const nextTags = tags.split(',').map(tag => tag.trim()).filter(Boolean); await api.updateEntry(token, song.id, { rating, tags: nextTags, notes, favorite }); onSaved({ ...song, rating, tags: nextTags, notes, favorite }); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Could not update this song.'); } }; return <div className="modal-backdrop" onMouseDown={onClose}><form className="add-modal" onMouseDown={e => e.stopPropagation()} onSubmit={save}><button type="button" className="modal-close" onClick={onClose}>x</button><p className="eyebrow">EDIT JOURNAL ENTRY</p><h2>{song.title}</h2><label>Rating<select value={rating} onChange={e => setRating(Number(e.target.value))}>{[.5,1,1.5,2,2.5,3,3.5,4,4.5,5].map(value => <option key={value} value={value}>{value.toFixed(1)} / 5</option>)}</select></label><label>Tags<input value={tags} onChange={e => setTags(e.target.value)} list="saved-tags"/></label><label>Notes<textarea value={notes} onChange={e => setNotes(e.target.value)}/></label><label className="favorite-toggle"><input type="checkbox" checked={favorite} onChange={e => setFavorite(e.target.checked)}/>Favorite this song</label>{error && <p className="login-error">{error}</p>}<button className="login-submit">Save changes</button></form></div>; }

function SearchMusicModal({ token, onClose, onSaved }: { token: string; onClose: () => void; onSaved: (song: Song) => void }) {
  const [query, setQuery] = useState(''); const [groups, setGroups] = useState<SearchGroup[]>([]); const [selected, setSelected] = useState<SearchResult | null>(null); const [rating, setRating] = useState(4); const [tags, setTags] = useState(''); const [suggestions, setSuggestions] = useState<string[]>([]); const [notes, setNotes] = useState(''); const [favorite, setFavorite] = useState(false); const [error, setError] = useState(''); const [searching, setSearching] = useState(false); const [saving, setSaving] = useState(false); useEffect(() => { api.tags(token).then(response => setSuggestions(response.data.map(tag => tag.name))).catch(() => undefined); }, [token]);
  const search = async (e: FormEvent) => { e.preventDefault(); if (query.trim().length < 2) return; setSearching(true); setError(''); try { setGroups((await api.searchMusic(token, query)).groups); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Could not search providers.'); } finally { setSearching(false); } };
  const save = async (e: FormEvent) => { e.preventDefault(); if (!selected) return; const journalTags = tags.split(',').map(tag => tag.trim()).filter(Boolean); setSaving(true); setError(''); try { await api.saveProviderSong(token, selected, { rating, favorite, tags: journalTags, notes }); onSaved({ title: selected.title, artist: selected.artists.join(', '), album: selected.album || selected.channel || 'Single', tag: journalTags[0] || 'Journal entry', rating, artworkUrl: selected.artworkUrl, favorite, added: 'Today' }); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Could not save this song.'); } finally { setSaving(false); } };
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="add-modal search-modal" onMouseDown={e => e.stopPropagation()}><button type="button" className="modal-close" onClick={onClose}>x</button><p className="eyebrow">UNIFIED MUSIC SEARCH</p><h2>{selected ? 'Make it yours' : 'Find a song'}</h2>{!selected ? <><form className="provider-search" onSubmit={search}><input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Search Spotify and YouTube"/><button className="login-submit" disabled={searching}>{searching ? 'Searching...' : 'Search'}</button></form>{error && <p className="login-error">{error}</p>}<div className="provider-results">{groups.map(group => <section key={group.provider}><div className="provider-heading"><b>{group.provider === 'spotify' ? 'Spotify' : 'YouTube'}</b><span>{group.enabled ? '' : 'Not configured'}</span></div>{group.message && <p className="provider-message">{group.message}</p>}{group.results.map(result => <button className="provider-result" onClick={() => setSelected(result)} key={`${result.provider}-${result.providerId}`}><img src={result.artworkUrl} alt=""/><span><b>{result.title}</b><small>{result.artists.join(', ')}{result.album ? ` - ${result.album}` : ''}</small></span><em>Choose</em></button>)}</section>)}</div></> : <form onSubmit={save}><button type="button" className="back-search" onClick={() => setSelected(null)}>Back to results</button><div className="chosen-song">{selected.artworkUrl && <img src={selected.artworkUrl} alt=""/>}<div><b>{selected.title}</b><span>{selected.artists.join(', ')} - {selected.provider}</span></div></div><label>Rating<select value={rating} onChange={e => setRating(Number(e.target.value))}>{[.5,1,1.5,2,2.5,3,3.5,4,4.5,5].map(value => <option key={value} value={value}>{value.toFixed(1)} / 5</option>)}</select></label><label>Tags<input value={tags} onChange={e => setTags(e.target.value)} placeholder="Night drive, discovery" list="tag-suggestions"/><datalist id="tag-suggestions">{suggestions.map(tag => <option value={tag} key={tag}/>)}</datalist></label><label>Notes<textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="What does this song mean to you?"/></label><label className="favorite-toggle"><input type="checkbox" checked={favorite} onChange={e => setFavorite(e.target.checked)}/>Favorite this song</label>{error && <p className="login-error">{error}</p>}<button className="login-submit" disabled={saving}>{saving ? 'Saving...' : 'Save to journal'}</button></form>}</section></div>;
}

function Dashboard({ username, token, theme, onToggleTheme, onLogout }: { username: string; token: string; theme: Theme; onToggleTheme: () => void; onLogout: () => void }) {
  const [active, setActive] = useState('Overview'); const [search, setSearch] = useState(''); const [library, setLibrary] = useState<Song[]>([]); const [adding, setAdding] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.library(token).then(response => setLibrary(response.data.map(toSong))).catch(() => setError('Your saved library could not be loaded.')); }, [token]);
  const visible = useMemo(() => library.filter(song => `${song.title} ${song.artist} ${song.album} ${song.tag}`.toLowerCase().includes(search.toLowerCase())), [library, search]);
  const page = active === 'Settings' ? <SettingsPage theme={theme} onToggleTheme={onToggleTheme}/> : active === 'Collections' ? <CollectionsPage library={library}/> : active === 'Analytics' ? <AnalyticsPage library={library}/> : <><header><div><p className="eyebrow">YOUR PRIVATE MUSIC ARCHIVE</p><h1>Good evening, {username}</h1><p className="subhead">A little corner for the music that moves you.</p></div><button className="add-button" onClick={() => setAdding(true)}>Add music</button></header><div className="search"><span>Search</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search your library, notes, tags"/></div><section className="stats">{[[library.length,'Songs in your story'],[library.filter(s => s.favorite).length,'Favorite songs'],[library.length ? (library.reduce((sum,s) => sum+s.rating,0)/library.length).toFixed(1) : '0.0','Average rating'],[visible.length,'Matching songs']].map(([number,label],i) => <article key={String(label)}><span className={'stat-orb orb-'+i}>{['M','F','*','+'][i]}</span><div><strong>{number}</strong><p>{label}</p></div></article>)}</section><section className="library-section"><div className="section-heading"><div><p className="eyebrow">YOUR LIBRARY</p><h2>{active === 'Favorites' ? 'Favorite songs' : 'Your latest chapters'}</h2></div></div>{error && <p className="login-error">{error}</p>}<div className="song-grid">{visible.filter(song => active !== 'Favorites' || song.favorite).map(song => <article className="song-card" key={`${song.title}-${song.artist}`}><div className="cover" style={song.artworkUrl ? { backgroundImage: `url(${song.artworkUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' } : {}}><span>{song.favorite ? 'Favorite' : 'Journal'}</span></div><div className="song-info"><h3>{song.title}</h3><p>{song.artist}</p><div><Stars value={song.rating}/><span className="tag">{song.tag}</span></div></div></article>)}</div>{!visible.length && <p className="empty">Your saved songs will appear here after you add them from a provider search.</p>}</section></>;
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><b>Nikhar's</b><span>Music Journal</span></div></div><nav>{nav.map(item => <button key={item} className={active === item ? 'active' : ''} onClick={() => setActive(item)}><NavIcon name={item}/>{item}</button>)}</nav><div className="sidebar-bottom"><button onClick={onToggleTheme}>Appearance <span className="theme-label">{theme}</span></button><button onClick={() => setActive('Settings')}>Settings</button><button className="profile" onClick={onLogout}><div className="avatar">{username.slice(0,2).toUpperCase()}</div><div><b>{username}</b><span>Log out</span></div></button></div></aside><section className="content">{page}</section><nav className="mobile-nav">{nav.map(item => <button className={active === item ? 'active' : ''} onClick={() => setActive(item)} key={item}><NavIcon name={item}/>{item}</button>)}</nav>{adding && <SearchMusicModal token={token} onClose={() => setAdding(false)} onSaved={song => { setLibrary(items => [song, ...items]); setAdding(false); }}/>}</main>;
}

function LoginScreen({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (e: FormEvent) => { e.preventDefault(); setLoading(true); setError(''); try { onAuthenticated(await api.login(username, password)); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'The journal could not be reached.'); } finally { setLoading(false); } }; return <main className="login-page"><div className="login-orb orb-one"></div><div className="login-orb orb-two"></div><section className="login-card"><div className="login-brand"><div className="brand-mark">M</div><span>Nikhar's Music Journal</span></div><div className="login-copy"><p className="eyebrow">YOUR PRIVATE MUSIC ARCHIVE</p><h1>Every song tells<br/>a story.</h1><p>Sign in to return to the memories behind your music.</p></div><form onSubmit={submit}><label>Username<input autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} required/></label><label>Password<input autoComplete="current-password" type="password" value={password} onChange={e => setPassword(e.target.value)} required/></label>{error && <p className="login-error">{error}</p>}<button className="login-submit" disabled={loading}>{loading ? 'Opening your journal...' : 'Enter your journal'}</button></form></section></main>; }

function App() { const [session, setSession] = useState<Session | null>(() => { try { const saved = localStorage.getItem('music-journal-session'); return saved ? JSON.parse(saved) as Session : null; } catch { return null; } }); const [theme, setTheme] = useState<Theme>(() => localStorage.getItem('music-journal-theme') === 'light' ? 'light' : 'dark'); useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('music-journal-theme', theme); }, [theme]); const authenticate = (next: Session) => { localStorage.setItem('music-journal-session', JSON.stringify(next)); setSession(next); }; const logout = () => { localStorage.removeItem('music-journal-session'); setSession(null); }; return session ? <Dashboard username={session.user.username} token={session.token} theme={theme} onToggleTheme={() => setTheme(value => value === 'dark' ? 'light' : 'dark')} onLogout={logout}/> : <LoginScreen onAuthenticated={authenticate}/>; }
createRoot(document.getElementById('root')!).render(<App/>);
